r Implementation of Endpoint for Creating Cards and Topping up Issuing Balance
manastech/stripe.cr pull request #1
Opened 2023-03-15 19:26 UTC by bolom

Implement the missing endpoints that would enable the creation of a card and the topping up of Issuing Balance

**Issuing#Card#**
- create
- update

**Issuing#CardHolder**
- create
- update

TopUp
- creata
- update
- cancel

2023-03-16 11:15 UTC, ysbaddaden reviewed
I can't really review the actual code, I don't know much about Stripe and the stripe shard even less.

It looks acceptable as per the shard. It ain't the best Crystal (or even Ruby) and seems to abuse reopening types (what's wrong with a single file per type?) but also macros to inject identical methods, when mixins would do the job just fine.

I only noted a few typos. A `crystal tool format` to fix the indentation and whitespace issues, then please upstream the pull request. 

Just don't merge here, `master` should reflect `upstream`, you can use this branch in the meantime!

2023-03-16 11:15 UTC, ysbaddaden commented on src/stripe/methods/core/issuing/create_card.cr
> +    {% for x in %w(cardholder currency type  status replacement_reason  shipping metadata) %}
You already added `cardholder`, `currency` and `type` above.

Looking at the upstream shard, you should just use the macro loop instead of fixed calls to `builder#add`. The `cardholder.nil?` is always false and will be optimized away by LLVM.

2023-03-16 11:15 UTC, ysbaddaden commented on spec/stripe/methods/issuing/card_spec.cr
> +  it "retrive card" do
```suggestion
  it "retrieve card" do
```

I noticed the same typo in a few other places.

2023-03-16 11:15 UTC, ysbaddaden commented on spec/support/retrieve_card.json
> +    "email": "qmiller+test1@manas.com.ar",
Let's avoid real names & emails in fixtures, be it yours, or worse: Quinton's!

This applies to all the JSON response fixtures.

2023-03-16 11:15 UTC, ysbaddaden commented on spec/support/retrive_topup.json
Typo in the filename: `retrieve_topup.json`

2023-03-16 12:36 UTC, bolom commented
@ysbaddaden Totally agree, the code's messy. Not sure why they made separate files for methods. Should I refactor or just move on?

> Just don't merge here, master should reflect upstream, you can use this branch in the meantime!

Yep

2023-03-16 12:42 UTC, bolom commented on src/stripe/methods/core/issuing/create_card.cr
> +    {% for x in %w(cardholder currency type  status replacement_reason  shipping metadata) %}
@ysbaddaden  mmm, It looks like you're reviewing an outdated version. I have refactored the latest version for that,

```
class Stripe::Issuing::Card
  def self.create(params = {} of String => String) : self
    io = IO::Memory.new
    builder = ParamsBuilder.new(io)

    params.each do |key, value|
      builder.add("#{key}", value)
    end

    response = Stripe.client.post("/v1/issuing/cards", form: io.to_s)
    if response.status_code == 200
      Issuing::Card.from_json(response.body)
    else
      raise Error.from_json(response.body, "error")
    end
  end
end
```

2023-03-16 13:51 UTC, ysbaddaden commented on src/stripe/methods/core/issuing/create_card.cr
> +    {% for x in %w(cardholder currency type  status replacement_reason  shipping metadata) %}
I can't find any `create_x` or `update_x` method in the shard that takes a blunt hash: they _all_ have explicitly typed method arguments. See for example [create_charge.rb](https://github.com/confact/stripe.cr/blob/master/src/stripe/methods/core/charges/create_charge.cr).

The point is that you can't pass arbitrary keys and values: Crystal will complain when some required arguments are missing or some values are invalid.

What I reviewed is actually closer to what's expected by the shard author.

2023-03-20 10:42 UTC, ysbaddaden commented on shard.yml
> +    github: exempletech/webmock.cr
```suggestion
    github: manastech/webmock.cr
```

2023-03-22 11:03 UTC, caspiano requested changes

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/issuing/card.cr
> +  struct SpendingControls
Looks like the rest of the library uses classes for the API objects.

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/topup.cr
> +  getter status : String
This should be an enum, [see here](https://stripe.com/docs/api/topups/object#topup_object-status)

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/issuing/card.cr
> +    property allowed_categories : Array(String)?
As I mentioned on our call, generally avoid mutable structs in Crystal.
[Here's some explanation](https://crystal-lang.org/reference/1.7/syntax_and_semantics/structs.html#structs)

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/issuing/card.cr
> +    property allowed_categories : Array(String)?
It also looks like the rest of the library sticks to getters for the attributes of API objects

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/issuing/cardholder.cr
> +    status : String? = nil,
This should be a union of `String` and `Status`. I would take a look over these methods to see if one can pass the corresponding enum to the method.

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/topup.cr
> +  getter source : Hash(String, Bool | Int32 | String | Hash(String, String? | Hash(String, String?) | Int32) | Nil)?
[There's an entity for this](https://github.com/manastech/stripe.cr/blob/master/src/stripe/objects/core/source.cr#L2)

2023-03-22 11:03 UTC, caspiano commented on src/stripe/objects/core/issuing/cardholder.cr
> +  getter requirements : Hash(String, String | Array(String) | Nil)?
I think there's some properties on this object https://stripe.com/docs/api/issuing/cardholders/object#issuing_cardholder_object-requirements

2023-03-22 11:03 UTC, caspiano commented on src/stripe/methods/update.cr
> +end
This could use some manual formatting

2023-04-10 01:41 UTC, closed without merging